# -*- coding: utf-8 -*-
"""ds1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TtqQHBYHTCUkplKJAtu8c4GmDn6N7kAG
"""

# Define two sets
E = {0, 1, 2, 3, 4, 5, 6, 8}
N = {2, 4, 6, 8, 10}

# Calculate and print the union of E and N
union_result = E.union(N)
print(f"Union of E and N is {union_result}")

# Calculate and print the intersection of E and N
intersection_result = E.intersection(N)
print(f"Intersection of E and N is {intersection_result}")

# Calculate and print the difference of E and N (E - N)
difference_result = E.difference(N)
print(f"Difference of E and N is {difference_result}")

# Calculate and print the symmetric difference of E and N
symmetric_difference_result = E.symmetric_difference(N)
print(f"Symmetric difference of E and N is {symmetric_difference_result}")

